# Generated by Django 3.2.12 on 2022-02-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('image', models.ImageField(upload_to='screenshots/%Y/%m/%d/%H/%M/')),
            ],
        ),
    ]
