# Generated by Django 3.2.12 on 2022-02-27 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emma', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screenshot',
            old_name='num',
            new_name='display',
        ),
    ]
