# Generated by Django 3.2.12 on 2022-02-28 17:51

from django.db import migrations, models
import emma.storage


class Migration(migrations.Migration):

    dependencies = [
        ('emma', '0002_rename_num_screenshot_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='image',
            field=models.ImageField(storage=emma.storage.ContentAddressableStorage, upload_to='screenshots/%Y/%m/%d/%H/%M/'),
        ),
    ]
